import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
} from "../components/sharedstyles";
import Cards from "../components/cards";
import GridHero from "../components/GridHero";
import StoriesList from "../components/StoriesList"




export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description> 



         <Cards />
      </Main>  */}

      {/* <GridHero /> */}

      <StoriesList />

    </>
  );
}
